on:
  workflow_dispatch:

jobs:
  job1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [14.x, 15.x, 16.x]
    runs-on: ${{ martix.os }}  
    steps:
    - uses: actions/setup-node@v5.0.0
      with:
        node-version: ${{ martix.node_version }}
  
