on:
  workflow_dispatch:

jobs:
  hybrid_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a command in ubuntu vm
        run: echo "This runs on the ubuntu VM"

      - name: Run a command in alpine container
        uses: docker://alpine:3.14
        with:
          entrypoint: /bin/sh
          args: |
            -c "echo 'This runs on alpine container'"
